### ISSUE TITLE
Migrate to pnpm

### ISSUE THREAD

**Issue by unclamped** [replugged-org/replugged#10]
pnpm is a great piece of software which, as the name says, is a performant version of npm. Powercord/rePlugged's description tells us how it's supposed to be a "lightweight client mod focused on simplicity and performance", which seems to fit well with pnpm's features and functionality.

https://pnpm.io/

**Comment by asportnoy** [comment]
I personally use pnpm with this and have no issues. If you'd like to use it locally, you are more than welcome to. But for most users it's just an extra step and more issues to deal with.

**Comment by asportnoy** [comment]
Closing this per above comment
