### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by zachjmurphy** [replugged-org/replugged#106]
**Describe the feature request**
The folder structure seems unnecessarily complicated, `Replugged/src/powercord/plugins` is where the plugins are located for example, while other mods have them located in a easy and simple folder structure such as BetterDiscord for example which just has a folder in `AppData` that has a `themes` and `plugins` folder.

**What Plugin would it be for?**
Repository

**Expected behavior**
A less confusing folder structure and or easier access to plugins and themes.

**Comment by FifiTheBulldog** [comment]
This is part of our roadmap (#92), not sure exactly when it'll happen but it's planned.

**Comment by asportnoy** [comment]
Dupe #92
