### ISSUE TITLE
Move settings for formerly built-in plugins

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#114]
Add a migration script (see src/Powercord/migrations) to rename settings files from formerly built in plugins (eg pc-tags) to the non-pc-prefixed version.

Also update coremods and other built-in settings files to be rp-whatever instead of pc-whatever

If the target file already exists, just delete the old file.

**Comment by bop34** [comment]
I'll do this

**Comment by asportnoy** [comment]
Make sure to Open PRs in the other plugins

**Comment by DracoClaw** [comment]
Claiming this, already have a pr open
