### ISSUE TITLE
[Feature Request] Make unused plugin/theme store button link to plugins/themes channel

### ISSUE THREAD

**Issue by FnigePython** [replugged-org/replugged#116]
**Describe the feature request**
Given that a plugin or a theme store probably wont exist since the channels on the discord work well enough. The button should link to #plugin-links or #theme-links instead

**What Plugin would it be for?**
N/A

**Expected behavior**
(Can be applied for themes too, not doing so to keep it simple)
Upon entering the Plugins tab within settings, you should be able to press the medium sized blue button.

If you are in the server, pressing the blue button within the Plugins tab should bring you to #plugin-links where you can explore plugins
If you arent in the server, pressing the blue button should instead give you the invite to the server to join

**Comment by asportnoy** [comment]
No longer applies
