### ISSUE TITLE
[Feature Request] Bring back the old "new" webpack backend.

### ISSUE THREAD

**Issue by m00nwtchr** [replugged-org/replugged#119]
In newer versions of Electron, Discord only works with contextIsolation enabled, and when contextIsolation (on newer versions of Electron) is enabled the `powercord/webpack` module doesn't work, infinitely looping and stopping replugged from loading without any errors (because `webpackChunkdiscord_app` isn't available in the preload script). I know this isn't a problem with a standard Discord install, for now, but I imagine it would be when Discord updates its electron version, and this would make it possible to use replugged for people who run Discord with a newer version of electron (e.g. for better wayland support on Linux)

**Comment by lleyton** [comment]
Gonna heavily prioritize this one. Today, Discord updated Electron to version 17 on the development branch.

**Comment by CanadaHonk** [comment]
Context isolation is already enabled and has been for months, the issue is 17 fixes the unintended context leak which Powercord uses. Not related to context isolation being changed.

**Comment by m00nwtchr** [comment]
Yes

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
