### ISSUE TITLE
Plugin/theme install deep link

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#13]
Set up some kind of deep linking to initiate plugin install from the browser. Should have confirmation alert in-app similar to existing command.
Create HTML/markdown for button that can be put on github READMEs for easy install

**Comment by 112batman** [comment]
A way to do this would be using url protocols (or whatever they're called) eg. `replugged-install-plugin://owner/repo/branch` (and a different one for themes) which could be used as a link target on an image in Markdown. Electron supports registering these handlers (Although I could not find if the old version Discord uses does). On MacOS and Linux however this requires adding data to the packaged electron app (Discord) and I do not see how this would be done, it'd have to be part of the injection process probably. Thoughts on implementing this?

The data sent to Replugged this way could be used to display an installation modal, this part would probably be easiest to implement.

I can start working on this in about a week when I get back from vacation but feel free to share ideas or maybe implement this (or a different solution) before then.

PS.
In Electron V14 you register these handlers with `app.setAsDefaultProtocolClient` an example is here https://www.electronjs.org/docs/v14-x-y/tutorial/launch-app-from-url-in-another-app

**Comment by Vendicated** [comment]
to be precise, they need to be added to the .desktop file on Linux and likely its equivalent on macos. Discords desktop file will likely be in /usr/share/application/Discord(-branch).desktop. The easiest way to modify it without touching the original is to copy it over to /usr/local/share/applications and then editing that, on unplug it can just be deleted again. However, once discord is updated this desktop file could change which somehow needs to be accounted for.

**Comment by LandenStephenss** [comment]
> A way to do this would be using url protocols (or whatever they're called) eg. replugged-install-plugin://owner/repo/branch

for future reference they're usually called "deep links"

**Comment by asportnoy** [comment]
This issue is available! If you would like to take it, please add a comment so I can assign it to you.

**Comment by 112batman** [comment]
You can assign me

**Comment by Deepfried-Chips** [comment]
I can take this on, i'd just need to read up a bit more on protocols in electron

**Comment by Deepfried-Chips** [comment]
protocols might work out of the box on macos possibly, since a packed app is executing replugged's code and stuff
