### ISSUE TITLE
Make themes use manifest.json instead of powercord_manifest.json

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#135]
If there is a powercord_manifest.json, that should be used instead. You can check if there's a `theme` key to know whether or not it's a theme. Make sure to update the various installer stuff to save them correctly.

**Comment by LandenStephenss** [comment]
could just run the already existing manifest validation

**Comment by SomeAspy** [comment]
I'll try this I suppose

**Comment by SomeAspy** [comment]
I'll take

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
