### ISSUE TITLE
replugged randomly crashes

### ISSUE THREAD

**Issue by josesilveiraa** [replugged-org/replugged#144]
**Describe the bug**
Replugged randomly crashes every time.

**To Reproduce**
Use latest Replugged version and wait some time, maybe change between channels. You'll notice that the members won't load anymore.

**Expected behavior**
It isn't supposed to crash.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Replugged version: e67d9a6

**Additional context**
 - [X] I checked if Discord and/or Replugged are up to date
 - [X] I made sure this is not related to an external plugin or a theme

**Comment by bop34** [comment]
I am also on arch Linux and am not experiencing this. This seems like a plugin issue. Also, saying discord crashes with no logs, debug info, or any indication to what might be causing it is not helpful.

**Comment by LeafyLuigi** [comment]
Enabling "Preserve log" under the console settings you should be able to keep the log and read the last known error and post that.

I'm currently experiencing something like this and for me this seems to be the last error
![image](https://user-images.githubusercontent.com/13402990/186325636-0c8ecc4d-81aa-4fbf-b5bf-b9fab91d0913.png)

From what I can tell receiving a message has the chance of causing a crash. Replugged version `940565c`, main branch, Canary version `ec6e8b2`.
