### ISSUE TITLE
[Feature Request] futureproof webpack.getLazyLoadedChunkIdsByModule

### ISSUE THREAD

**Issue by Vap0r1ze** [replugged-org/replugged#145]
[`getLazyLoadedChunkIdsByModuleId`](https://github.com/replugged-org/replugged/blob/main/src/fake_node_modules/powercord/webpack/index.js#L138) assumes that webpack's [require.ensure](https://webpack.js.org/api/module-methods/#requireensure) terses to `requireArgument`.e

It should probably grab the property from the main webpack chunk so it doesnt break if discord updates their webpack and this changes

**Comment by Vap0r1ze** [comment]
i plan on doing this just wanted an issue open as a reminder

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
