### ISSUE TITLE
Monaco CSS snippets

### ISSUE THREAD

**Issue by botatooo** [replugged-org/replugged#15]
**Describe the feature request**
Instead of using the current CodeMirror implementation, it would be nice to see the css snippets editor using monaco.

**Comment by asportnoy** [comment]
This issue is available! If you would like to take it, please add a comment so I can assign it to you.

**Comment by French-Cat** [comment]
I shall attempt this.

**Comment by French-Cat** [comment]
I have given up on this. 🧍‍♂️ @asportnoy

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
