### ISSUE TITLE
Change all variables, classes, file names, etc, to Replugged instead of Powercord

### ISSUE THREAD

**Issue by bop34** [replugged-org/replugged#151]
Problems that I can think of with this:
- Breaks a lot of plugins
- Requires a lot of work but has no visible impact for the user

**Comment by Vap0r1ze** [comment]
u misspelled embarrassment in the label

**Comment by asportnoy** [comment]
I think a good starting place for this would be:
- Rename `src/Powercord` to `src/Replugged`
- Rename `src/fake_node_modules/powercord` to `src/fake_node_modules/replugged`
- Add `replugged/*` require (keep `powercord/*` for backwards compatibility)
- Rename global var `powercord` to `replugged` and create another variable (`powercord`) pointing to it for backwards compatibility
- Rename global var `PowercordNative` to `RepluggedNative` and create another variable (`PowercordNative`) pointing to it for backwards compatibility

**Comment by bop34** [comment]
I'll do this one.

**Comment by asportnoy** [comment]
Let's merge #153 before we merge this, should make things easier

**Comment by DavidNyan10** [comment]
Quesiton: would this break for existing users who migrated from powercord?

**Comment by asportnoy** [comment]
This will be added the rewrite, closing this.
