### ISSUE TITLE
Quick CSS Inconsistent

### ISSUE THREAD

**Issue by Snare-Hawk** [replugged-org/replugged#156]
**Describe the bug**
Quick CSS is incredibly inconsistent with everything. It constantly crashes whenever I have it popped out never with a rhyme or reason. I am also unable to paste anything when Quick CSS is popped out, another inconsistent error that has affected a few others.

**To Reproduce**
Use Quick CSS
Suffer

**Expected behavior**
Quick CSS is wholesome and doesn't crash for no reason.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19044)
 - Replugged version: Replugged main (66c360d)

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
Please.

**Comment by asportnoy** [comment]
Dupe #71
