### ISSUE TITLE
Installing Plugins/Themes via Message Crashes

### ISSUE THREAD

**Issue by Snare-Hawk** [replugged-org/replugged#174]
**Describe the bug**
When trying to install a plugin in the message bar (`.install <plugin/theme link>`), the client crashes when the installation confirmation screen is supposed to appear.

**To Reproduce**
Attempt to install a plugin or theme from the message bar.

**Expected behavior**
The installation confirmation pop-up should appear allowing me to complete installing the plugin or theme.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19044
 - Replugged version: Replugged main (54c8919)

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
Before I had updated to the latest version, I had noticed that pop-up was appearing very long after I had input the install command. This still seems to be present, as can be seen in this [video](https://cdn.discordapp.com/attachments/1000955987739541585/1014702431902388275/2022-08-31_20-50-40.mp4) (This is on the Replugged server, so here's the [message link](https://discord.com/channels/1000926524452647132/1000955987739541585/1014702433315864706) to it as well.)

**Comment by asportnoy** [comment]
Cannot reproduce

**Comment by asportnoy** [comment]
Nevermind, I can reproduce
