### ISSUE TITLE
[Feature Request] Flatpak installation

### ISSUE THREAD

**Issue by yurifuko** [replugged-org/replugged#176]
**Describe the feature request**
option to install on Discord Flatpak, possibly a "flatpak" branch/option?

**Expected behavior**
replugged on discord installed with flatpak, currently installation only supports unsandboxed/native

possibly helpful - location of core.asar, index.js and package.json:
`~/.var/app/com.discordapp.Discord/config/discord/0.0.19/modules/discord_desktop_core/`

**Comment by Vendicated** [comment]
Already a thing https://github.com/replugged-org/replugged/pull/149
