### ISSUE TITLE
package-lock.json causes automatic updates to frequently fail

### ISSUE THREAD

**Issue by Gorialis** [replugged-org/replugged#185]
**Describe the bug**
The removal of `package-lock.json` from gitignore as in 3ed728cd91ed3314b2abda43de6c103b19d0864b results in it getting modified.

**To Reproduce**
- Update replugged through the updater
- The update succeeds, but as part of the update, the package-lock becomes modified and gets recognized by git as an unstaged change:
![image](https://user-images.githubusercontent.com/8049998/188333824-c947d1f6-163f-4acb-86b7-9aabfbb273ac.png)
- Next time an update is available, the unstaged change blocks the HEAD from being moved, and automatic updates cannot continue until manual intervention (such as `git restore package-lock.json`) is performed.

**Expected behavior**
Ideally this would not even happen (not ignoring package-lock implies we're aiming for reproducibility, but it getting overwritten means we are using commands incompatible with this - maybe using `npm i` instead of `npm ci` etc), but if not this, replugged should at least be able to identify and rectify this issue when it happens.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Replugged version: Official/2b30c70/main

**Additional context**
 - [X] I checked if Discord and/or Replugged are up to date
 - [X] I made sure this is not related to an external plugin or a theme
 
It is possible that existence of plugins is to do with the issue (such that it's not reproducible without ones that meet the conditions - my suspicion would be maybe if a plugin requires an extra dependency). However, I don't think this is to do with any plugin in particular, since a source code check confirms none of the ones I use touch the external repo. I am not familiar with whether powercord/replugged scours plugins for dependencies, but if it does, it's possible that installation with regards to them is to blame for this.

**Comment by lexisother** [comment]
My fix would be to just run `git checkout -- package-lock.json` after an update. It resets the file and all is well.

**Comment by asportnoy** [comment]
I updated the package lock for the current version which should solve this for this version. I'll need to make sure I update it when I bump again in the future. We should set up a GitHub workflow to test if the package lock is up to date to ensure we don't have issues in the future. We might also want to set up a pre-commit hook for both that and regular linting.

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
