### ISSUE TITLE
Add warning to wiki that the replugged is NOT copied to a standard location when installing

### ISSUE THREAD

**Issue by rhysperry111** [replugged-org/replugged#193]
I think it's a fairly reasonable assumption for a user to make that replugged will copy itself to a standard location, rather than just linking to wherever it had been cloned into.

Could the wiki be updated with at least a warning explaining the behaviour of the installer?

Not sure if I'm the first person to make this mistake, but I cloned the repo into `/tmp` when I was installing earlier this week, and only realised the problem when I rebooted this morning.

**Comment by asportnoy** [comment]
This will be added the rewrite, closing this.
