### ISSUE TITLE
Changelog backdrop not disappearing

### ISSUE THREAD

**Issue by Strencher** [replugged-org/replugged#20]
**Describe the bug**
Clicking the backdrop to close the modal, closes the modal but still keeps the backdrop shown.

**To Reproduce**
1. Fresh install replugged
2. Open the discord client
3. Click the backdrop __once__

**Expected behavior**
The changelog modal closes entirely.

**Desktop (please complete the following information):**
 - OS: Windows 11 Insiders
 - Discord Channel: Canary
 - Replugged version:  https://github.com/replugged-org/replugged/tree/dc636db6e1229e1facaffe4811277bc15eb72108

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by asportnoy** [comment]
This issue is available! If you would like to take it, please add a comment so I can assign it to you.

**Comment by Deepfried-Chips** [comment]
could take it on, since it just seems to be a problem of replugged not detecting the prompt closing

**Comment by lleyton** [comment]
closed by #37
