### ISSUE TITLE
Skip Update doesn't work at all

### ISSUE THREAD

**Issue by vaguerant** [replugged-org/replugged#200]
**Describe the bug**
Selecting Skip Update on an update you're not interested just prompts you to update again the next time updates are checked (e.g. in 15 minutes if that's your update check interval), even though no new updates have been pushed.

**To Reproduce**
Get an update toast notification, Open Updater, Skip Update, go back to what you were doing and wait for the toast to come back again.

**Expected behavior**
The popup should not return until there's a *different* update to the one you skipped. Otherwise, what are we even doing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Replugged version: e41fcaa

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
   - Technically I checked that it's **not** up-to-date, but it's one manifest update behind current HEAD
 - [ ] I made sure this is not related to an external plugin or a theme
   - I didn't do this, I'm a bad person
 
I'm testing with "Check manifest version" enabled, I don't know if this behavior also affects people pulling down every commit.

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
