### ISSUE TITLE
Canary no longer is plugged with release 149251 (1fda10a)

### ISSUE THREAD

**Issue by lunaisnotaboy** [replugged-org/replugged#202]
**Describe the bug**

Despite unplugging and replugging several times, Replugged is no longer working in Discord Canary 149251 (1fda10a).

**To Reproduce**

Use the latest version of Discord Canary.

**Expected behavior**

The client to actually be there.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.22622) [it's actually Windows 11, but whatever...]
 - Replugged version: N/A (can't check using the UI; Git hash is 3a3f46baa901f5ea003770dafe1c0ab31c8ac138)

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
Also showing up in Powercord (see powercord-org/powercord#677), so not limited to Replugged.

**Comment by SomeAspy** [comment]
This is a [known issue](https://discord.gg/hwHzNQxJ) and a resolution is currently in the works.
You can stay updated by joining the [Discord Server](https://discord.gg/hwHzNQxJ)
