### ISSUE TITLE
Unable to Inject

### ISSUE THREAD

**Issue by dhanrahl** [replugged-org/replugged#203]
**Describe the bug**
Unable to inject RePlugged

**To Reproduce**
npm run plug [Version]

**Expected behavior**
Well, inject I suppose.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19044.2006]
 - Replugged version: Latest Release

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
Error output in file below.
[2022-09-26T21_14_03_327Z-debug.log](https://github.com/replugged-org/replugged/files/9649738/2022-09-26T21_14_03_327Z-debug.log)

**Comment by dhanrahl** [comment]
Noticed log doesn't output the error in console. Additional information:

`PS C:\Users\D'han Rahl\replugged> npm run plug Stable

> replugged@3.0.15-t1 plug C:\Users\D'han Rahl\replugged
> node injectors/index.js inject --no-exit-codes "Stable"

C:\Users\D'han Rahl\replugged\injectors\index.js:37
let platform = process.argv[4]?.toLowerCase();
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! replugged@3.0.15-t1 plug: `node injectors/index.js inject --no-exit-codes "Stable"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the replugged@3.0.15-t1 plug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\D'han Rahl\AppData\Roaming\npm-cache\_logs\2022-09-26T21_14_03_327Z-debug.log`

**Comment by dhanrahl** [comment]
Went in and removed `?.toLowerCase()` from index.js:37 and was able to actually run the script, but no injection on stable.

**Comment by Vendicated** [comment]
if removing that fixed it, you're running an ancient nodejs version. Update your nodejs.

Replugged also is completely broken for the time being so that's why it doesn't load even after a successful injection

**Comment by dhanrahl** [comment]
Alright, I"ll update my node. I saw it was broken for Canary but hadn't seen anything about Stable yet.

**Comment by dhanrahl** [comment]
That indeed fixed the issue, thank you.
