### ISSUE TITLE
Node.js is deprecated. Please stop using it.

### ISSUE THREAD

**Issue by MagmaBro123** [replugged-org/replugged#204]
**Describe the bug**
Title.

**To Reproduce**
Try installing Replugged.

Node.js was reinstalled. Didn't work either.
![image](https://user-images.githubusercontent.com/51277766/192641885-bb8cf0f8-9cdc-426b-870c-95347f792c5d.png)

**Expected behavior**
Replugged being installed correctly.

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Replugged version: Unable to provide, as installation doesn't work.

**Additional context**
 - [X] I checked if Discord and/or Replugged are up to date
 - [X] I made sure this is not related to an external plugin or a theme
 (Can't even install, these shouldn't matter.)

**Comment by Vendicated** [comment]
this is irrelevant just ignore it

**Comment by MagmaBro123** [comment]
Plugged. Nothing changed within Discord.

**Comment by zachjmurphy** [comment]
@MagmaBro123 This is a [known issue](https://discord.gg/replugged).

**Comment by MagmaBro123** [comment]
Sorry.
