### ISSUE TITLE
The Future of Replugged

### ISSUE THREAD

**Issue by lleyton** [replugged-org/replugged#205]
**What?**

As of September 26, Discord has switched from Babel to SWC for minification. This change has broke the existing methods we used to search for Webpack modules, breaking Replugged as a whole (and many other client modifications.) Anything related to searching modules by name is broken (and will be for the foreseeable future.)

**Is Replugged going EOL?**

_We are not going EOL._

While the Replugged project as a whole isn't going anywhere, this current codebase should be considered deprecated. We are currently working on a successor built around these breaking changes, as much of the current codebase relies on these now broken methods. We do not have an ETA yet.

**What about my plugins?**

All existing Replugged/Powercord plugins **will not** work on the successor version. Because client modification in Discord has fundamentally changed, there is no way for us to provide the Powercord API. If you are a plugin developer, you will need to rewrite your plugins for this new version within this new paradigm. Theme developers should be mostly unaffected, except for manifest changes in this new version.

**Questions?**

For any further questions, feel free to join our [Discord server](https://discord.gg/eJasPnsNTm) or discuss within this issue. Thank you, to all of our contributors, and especially our lovely users.

**Comment by lleyton** [comment]
Thanks, I'll update the issue

**Comment by StarNumber12046** [comment]
updates?

**Comment by bop34** [comment]
> updates?

Updates will be announced, as has been stated on the discord

**Comment by StarNumber12046** [comment]
thanks, I joined now

**Comment by lleyton** [comment]
patience, neko
