### ISSUE TITLE
Not installing on linux

### ISSUE THREAD

**Issue by JustZvan** [replugged-org/replugged#209]
It doesn't work on my machine. It says "Replugged has been succesfully plugged :D" , but it doesn't show in discord.

**Comment by lleyton** [comment]
hmmmm, it's almost like there's a pinned issue about this

**Comment by milena-kos** [comment]
nah thats too difficult, you need to actually read stuff

**Comment by zvanm** [comment]
Wait, there is a pinned issue. Can you post the link please

**Comment by Captain8771** [comment]
im on mobile so i cant see pinned issues but i believe they mean [this one](https://github.com/replugged-org/replugged/issues/205#issue-1388598231)
