### ISSUE TITLE
Commands Coremod (switch to slash commands)

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#230]

**Comment by ShadiestGoat** [comment]
Hello, why was this removed from the Public release milestone?

**Comment by asportnoy** [comment]
While this is still a feature we want to implement, we don't _need_ it in order to publicly release. I cleaned up the things in that milestone so we can prioritize the things that we can't release without.

**Comment by Deepfried-Chips** [comment]
Has there been any progress done on this recently? As I might be willing to take it once I'm done with crash reporting

**Comment by asportnoy** [comment]
@12944qwerty is taking it. As for progress, i'm not sure.
