### ISSUE TITLE
Function injection errors/doesn't callback

### ISSUE THREAD

**Issue by Puyodead1** [replugged-org/replugged#271]
**Describe the bug**
When attempting to inject into a function, the first time it fails with an error, every other time it doesn't error but doesn't do anything (doesn't seem to actually be injecting/callback not getting called).

**To Reproduce**
Example code for reproduction:
```ts
import { AnyFunction, Injector, webpack } from "replugged";
const inject = new Injector();

function moduleFindFailed(moduleName: string): void {
  console.error(`Failed to find ${moduleName} module! Cannot continue`);
}

export async function start(): Promise<void> {
  const tagRenderMod = await webpack.waitForModule<{ x: AnyFunction }>(
    webpack.filters.bySource(".botTagCompact"),
  );
  if (!tagRenderMod) return moduleFindFailed("tagRenderMod");

  inject.instead(tagRenderMod, "x", (args, fn) => {
    console.log(`#########################`, args, fn);
    return fn(...args);
  });
}

export function stop(): void {
  inject.uninjectAll();
}
```

**Expected behavior**
Everytime, the function should be injected without errors, and it the callback should be called.

**Desktop**

- OS: Window 11 (22H2)
- Replugged version: [v4.0.0-beta0.17](https://github.com/replugged-org/replugged/releases/tag/v4.0.0-beta0.17)

**Additional context**

- [X] I checked if Discord and/or Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme

[Conversation in discord with asportnoy](https://canary.discord.com/channels/1000926524452647132/1000955966520557689/1053887327602216973)

**Comment by Penguin-Spy** [comment]
I'm able to work on this.
[relevant discussion in discord](https://discord.com/channels/1000926524452647132/1000955966520557689/1053971008865964052)

**Comment by asportnoy** [comment]
Assigned, thanks!
