### ISSUE TITLE
[Feature Request] Expose plugin directory path

### ISSUE THREAD

**Issue by SammCheese** [replugged-org/replugged#272]
**Describe the feature request**
Give me a way to get the plugin directory programmatically.

**What Plugin would it be for?** 
NO plugin. i just want a function in the replugged/RepluggedNative constant to get the current plugin directory

**Expected behavior**
Output should be a string that contains the path to the plugin directory

```js
RepluggedNative.plugins.path: () => "/home/sammy/replugged/plugins"
```

**Comment by asportnoy** [comment]
Should be added for themes/settings/quick css (file?) as well. Maybe also add a function to open to open the folder in finder/file explorer, but that part could wait.
