### ISSUE TITLE
webpack common constants is null on plugin load

### ISSUE THREAD

**Issue by Puyodead1** [replugged-org/replugged#276]
### Describe the bug

Upon first load of a plugin, webpack.common.constants is null which causes the plugin loading to fail.

### Reproduction steps

1. import something from webpack.common.constants such as `Permissions`
2. install plugin
3. refresh and let the plugin be auto loaded
4. observe error `TypeError: Cannot read properties of null (reading 'constants')`
5. now load the plugin manually with `await replugged.plugins.loadAll()`
6. reload the plugin `await replugged.plugins.reload("dev.replugged.PluginTemplate")`
7. Observe how the permissions are logged and the plugin loads without error

Reproduction Code:
```ts
import { Injector, webpack } from "replugged";
const { Permissions } = webpack.common.constants;

const inject = new Injector();

export async function start(): Promise<void> {
  console.log(Permissions);
}

export function stop(): void {
  inject.uninjectAll();
}
```

### Expected behavior

Plugin should load without error and webpack.common.constants should not be null

### Actual behavior

webpack.common.constants is null resulting in the plugin failing to load

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by asportnoy** [comment]
Pretty sure I know the issue here, will take a look later

**Comment by asportnoy** [comment]
@Puyodead1 `const { Permissions } = webpack.common.constants;` needs to be called from inside the `start` function. The common modules are not guaranteed to be defined until then.
