### ISSUE TITLE
Fix unplugging

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#277]
If Discord is running, renaming app.orig.asar to app.assr will fail. We should:
- Handle this error better and output a better error message, directing them to quit and try again
- Allow the command to run if there's an app.orig.asar but not app.asar (currently will say platform is not installed)

**Comment by SticksDev** [comment]
Will claim @asportnoy

**Comment by asportnoy** [comment]
@SticksDev Are you still able to take this?

**Comment by stressatoo** [comment]
Can reproduce, even with Discord NOT running

**Comment by Libroru** [comment]
Same issue here

**Comment by asportnoy** [comment]
No response from @SticksDev, marking this as available again.

**Comment by notKnei** [comment]
@asportnoy Claiming, pr soon

**Comment by asportnoy** [comment]
@notKnei This may conflict with my changes for #346. I recommend you either wait until that's merged or branch off of that for your changes.

**Comment by notKnei** [comment]
> @notKnei This may conflict with my changes for #346. I recommend you either wait until that's merged or branch off of that for your changes.

I'll wait for it to close, Seems like the only conflict will be the `scripts/inject/injector.ts` file so far
