### ISSUE TITLE
Turning off websecurity in electron

### ISSUE THREAD

**Issue by Sighyu** [replugged-org/replugged#282]
### Describe the feature request

I would like to have the ability to turn off websecurity in electron for the reason to use videos from local storage as my background in discord as it is easy to manage instead of using filehost which is not that reliable

### Why should this be added?

this will allow me to use the file:/// protocol to load local videos

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by MulverineX** [comment]
Replugged will be getting a main scope for plugins that you can use to interface with the filesystem

**Comment by MulverineX** [comment]
What exactly is the usecase here that you cannot do with standard web FS?

**Comment by Sighyu** [comment]
> What exactly is the usecase here that you cannot do with standard web FS?

Hi there could you show me some examples on web FS
