### ISSUE TITLE
Platform isn't installed

### ISSUE THREAD

**Issue by Tygo01** [replugged-org/replugged#286]
### Describe the bug

When you run `pnpm run plug <platform>` or `pnpm run unplug <platform>` it gives a error saying "Platform you specified isn't installed on this device!" even though it is installed, I have to reinstall discord to be able to use it again.
![image](https://user-images.githubusercontent.com/98230617/208969951-3818e060-8551-4707-ab42-338743349aa6.png)
![image](https://user-images.githubusercontent.com/98230617/208970010-43d57b09-d455-4ef9-9637-5daf92babfcb.png)

### Reproduction steps

1. Install replugged & plug
2. Try to unplug

### Expected behavior

Replugged gets unplugged / plugged

### Actual behavior

Platform you specified isn't installed on this device!

### Additional information

I did not confirm "I checked if Discord and Replugged are up to date" because I was trying to unplug, remove the replugged files, then install it again to update it.

### Please confirm the following

- [ ] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by asportnoy** [comment]
Likely due to #277

**Comment by stressatoo** [comment]
Can reproduce
