### ISSUE TITLE
Allow changing the path for plugin/theme folders

### ISSUE THREAD

**Issue by SomeAspy** [replugged-org/replugged#289]
### Describe the feature request

The user should be allowed to move the Replugged addon folders (Themes, CSS, Plugins) to a different location.
This would be ideally done via GUI but a command to do so would be acceptable during development.

### Why should this be added?

This is a feature that would be easier to add in earlier in development, as well as bringing more user customization to the table.

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by asportnoy** [comment]
Just create a symlink if you want that. This seems like an unnecessary and overcomplicated thing for a temporary issue.

**Comment by SomeAspy** [comment]
I talked to Fifi about this and I was told to just open an issue for it.
