### ISSUE TITLE
Update badge names to clarify that they're for Replugged

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#292]
Don't want someone thinking Staff = Discord staff or something like that

**Comment by EidanGar** [comment]
Hi, I came across this issue and would like to claim it. Before I begin working on it, I wanted to request some clarification on the task. What names do you want updated and what should they be updated to? Is there a code of conduct I should read specific to this project?

**Comment by asportnoy** [comment]
All of the badge names should start with "Replugged", IE "Replugged Contributor".

There isn't a code of conduct, but just make sure to format your code. There's an npm script to do that, as well as VSCode config to automatically format on save.

**Comment by EidanGar** [comment]
The code won't be a problem; I'm just new to git, speaking of which where do I find these badges?

**Comment by asportnoy** [comment]
See #287

**Comment by EidanGar** [comment]
@asportnoy, I understand that I should rename their file names, variables, imports, and string references, as well as make sure to change every occurrence. Also, I'm assuming that names that start with an uppercase letter should be written in PascalCase, while those that start with a lowercase letter should be written in camelCase, with no spaces in between. Is this correct?

**Comment by asportnoy** [comment]
You don't need to change any files or anything like that. Just update the tooltip message that is displayed to the user.

**Comment by EidanGar** [comment]
Oh, okay! That makes things much easier, thank you for clarifying. I'll go ahead and make the changes to the tooltip messages.

**Comment by EidanGar** [comment]
@asportnoy pulled
