### ISSUE TITLE
Add functions to DiscordNative to open folders in user's file manager

### ISSUE THREAD

**Issue by FifiTheBulldog** [replugged-org/replugged#305]
### Describe the feature request

Add functions to RepluggedNative to open the user's plugins/themes/quickcss/etc. folders from the window, using `electron.shell.openPath("path/to/folder")` over IPC. For example: `RepluggedNative.plugins.openFolder()`

### Why should this be added?

We can use this to open the user data folders from the settings UI, while respecting the sandbox and not exposing potentially sensitive information like full paths to the renderer.

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by CanadaHonk** [comment]
`DiscordNative.fileManager.showItemInFolder(path)` already exists?

**Comment by FifiTheBulldog** [comment]
We're not exposing any paths to the window, so that method doesn't get us anywhere.
