### ISSUE TITLE
Add check to see if user is already in the replugged discord server

### ISSUE THREAD

**Issue by Deepfried-Chips** [replugged-org/replugged#31]
**Describe the feature request**
Add a check to see if user is already in the replugged discord server to prevent the banner at the top, which gets relatively annoying when installing replugged on multiple devices

**What Plugin would it be for?**
pc-notices

**Comment by asportnoy** [comment]
This issue is available! If you would like to take it, please add a comment so I can assign it to you.

**Comment by Navnedia** [comment]
@asportnoy I'll take on this issue if it's still available.
