### ISSUE TITLE
[Feature Request] Automatically revert to last working install

### ISSUE THREAD

**Issue by 112batman** [replugged-org/replugged#32]
**Describe the feature request**
Implement a system that detects repeated crashes after installation of a plugin/theme, change of settings, Replugged update (etc.) and automatically reverts these changes to the last known working state.

This could be implemented in a system similar to A/B phones we're there's two installs of replugged (with all the plugins, themes, settings, etc. Being part of them) at all time. You're active install is for example slot A, you install a new plugin (so on slot A, the active slot) and restart. It seems this plugin is causing your Discord to crash repeatedly, Replugged detects this and switches to slot B we're these changes have yet to have been made. When slot B successfully launches it automatically overwrites the marked as broken slot A with the state from slot B (which is and stays the new active slot).

I hope that explanation makes sense, of course this could be implemented in many other ways.

This is not necessarily a very high-priority feature but would be nice for the end user to have as a sort of safeguard to prevents them from breaking their install and having to go trough the configuration files to fix it themselves (this becomes more important when things like theme/plugin stores are added allowing for full usage of Replugged without even knowing with file explorer is)

**Comment by botatooo** [comment]
There's a function under `DiscordNative.processUtils` that may be relevant to this issue:

```js
await DiscordNative.processUtils.getLastCrash();
````

**Comment by BlastoiseVeteran** [comment]
This would be fantastic. Ever since I've switched from Powercord to Replugged, I've encountered 2 crash loops to where I have to unplug it and just wait for an update.

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
