### ISSUE TITLE
General settings - control Replugged features

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#324]
- Change backend URL
- Enable/Disable Plugin Embeds (once added)
- Enable/Disable Experiments
- Enable/Disable devtools for non-canary clients
> ```js
> await DiscordNative.settings.get("DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING");
> await DiscordNative.settings.set("DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING", true);
> ```
- Enable/Disable badges

**Comment by lexisother** [comment]
yeah hi I've been waiting to do this since we like started the rewrite
