### ISSUE TITLE
Updater Settings

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#326]

**Comment by SammCheese** [comment]
I can give it a shot (I wouldn't have to make the entire updater backend right?)

**Comment by asportnoy** [comment]
Nope, the backend already exists, but may need minor tweaks to fit in with this.

**Comment by asportnoy** [comment]
@SammCheese as part of this, can you move the updater backend from the `managers` folder into the `apis` folder?

**Comment by SammCheese** [comment]
ya
