### ISSUE TITLE
Toasts

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#329]
Create a util for Discord toasts (seen when using the account switcher).

Implement the toast for things like enabling/disabling/uninstalling plugins as well as notifying the user that something went wrong.

**Comment by FifiTheBulldog** [comment]
Toasts are the little things that pop up in the upper middle of the screen with a short message and then disappear after a moment. Powercord's "toasts" are more appropriately described as alerts, which is the terminology we will use.
