### ISSUE TITLE
Add `getChannel` to channel common module

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#344]
Can be selected by props

**Comment by codewithfan** [comment]
I would love to work on this! @asportnoy

**Comment by asportnoy** [comment]
@codewithfan All yours!

**Comment by codewithfan** [comment]
Thank you! This will be my first contribution to this codebase. 

Is this the solution that is being sought for this issue @asportnoy?

`getChannel: (guildId?: string) => string | undefined;`

inside this file? see line 10

<img width="860" alt="Screenshot 2023-01-18 at 7 41 34 AM" src="https://user-images.githubusercontent.com/85418632/213200919-391f2519-a5e4-4be7-8efd-2b1c5deb5326.png">

**Comment by asportnoy** [comment]
`getChannel` is a separation module. You can query it by props in the console to see the parameters and run it to see the return type. Then, you'll need to add it to the exports here.

**Comment by Catalyst4222** [comment]
I can take this
