### ISSUE TITLE
Add RadioItem / Radio components

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#354]
See Appearance settings for example. `RadioItem` should include things like the title (likely children) and note, similar to `SwitchItem`. There may be a separate component for just the radio without the extra stuff, which we should try to get as well.

**Comment by FedeIlLeone** [comment]
I can take this. I've already started working on it.

**Comment by Tharki-God** [comment]
I have found the radio component and made a custom component with title and note .
check my plugin for details https://github.com/Tharki-God/ShowHiddenChannels
