### ISSUE TITLE
Components 

### ISSUE THREAD

**Issue by Tharki-God** [replugged-org/replugged#368]
### Describe the feature request

i want some components added to replugged.components because they are really common, for example a slider or dropdown 
as for the code: [Slider](https://github.com/Tharki-God/ShowNames/blob/main/src/Components/Slider.jsx),
 [SettingsGroup](https://github.com/Tharki-God/ShowHiddenChannels/tree/main/src/Components) a group of setting that can minimised or collapsed to just a string of text,
and [dropdowns](https://github.com/Tharki-God/PremiumScreenShare/blob/main/src/Components/Dropdown.jsx) and ig this is already in pull request but still [radiogroup](https://github.com/Tharki-God/ShowHiddenChannels/blob/main/src/Components/RadioGroup.jsx)

### Why should this be added?

because these are commonly used components

### Additional information

please unban me from the server pls

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by asportnoy** [comment]
Slider is being added in #366
SettingsGroup is already implemented (`replugged.components.Category`)
Radio is being added in #354

**Comment by Tharki-God** [comment]
That leaves dropdowns
