### ISSUE TITLE
Move webpack common into modules folder

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#384]
The components are also in that directory, so I think it makes sense to put common there as well.
Since there will only be one file left in the folder, you can move that into the modules folder as well and rename it to `webpack.ts`.

Of course, make sure to update the paths for any references to those files or folders, including in `tsconfig.json` and make sure this doesn't break any of Replugged's features or plugins.

**Comment by Kirito-Excalibur** [comment]
Can you assign me this?

**Comment by lexisother** [comment]
@Kirito-Excalibur Done.
