### ISSUE TITLE
error in plugging discord

### ISSUE THREAD

**Issue by NotPhantomX** [replugged-org/replugged#385]
### Describe the bug

In src/util.ts configPathFn returns /root/.config/replugged instead of /home/{username}/.config/replugged causing an error since the .config folder in /root/ does not exist. The cause seems to be process.env.XDG_CONFIG_HOME being set to /root at some point. Using bash instead of zsh or fish sets process.env.HOME to /root as well.

### Reproduction steps

1. sudo pnpm run plug --production canary

### Expected behavior

expected replugged to succeed in plugging discord

### Actual behavior

tries to create /root/.config/replugged and fails to create the path since /root/.config also does not exist.

### Additional information

```
sudo pnpm plug --production canary                         

> replugged@4.0.0-beta0.27 plug /home/phantomx/.replugged
> tsx scripts/inject/index.ts inject --no-exit-codes "--production" "canary"

node:fs:1394
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir '/root/.config/replugged'
    at mkdirSync (node:fs:1394:3)
    at Object.<anonymous> (/home/phantomx/.replugged/src/util.ts:22:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Object.v (/home/phantomx/.replugged/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.3.3/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:933)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/phantomx/.replugged/scripts/inject/injector.ts:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1120:14) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/root/.config/replugged'
}

Node.js v18.7.0
 ELIFECYCLE  Command failed with exit code 1.
```
Operating System: Fedora 37
Discord Version: Canary 173897 (8aa1dde)

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by bop34** [comment]
Cannot reproduce on Arch

**Comment by LizAinslie** [comment]
Just reproduced on arch, I cannot plug due to this issue.

![Repro](https://i-work-at-the.cocaine.institute/Lizzy63ec8e2aW4A2qJjsylDZ.png)

Here is my neofetch:
![neofetch](https://i-work-at-the.cocaine.institute/Lizzy63ec8e774ScetHGtCaSa.png)

**Comment by LizAinslie** [comment]
bumping because i still cannot plug my client. 

I'd love to see this fixed, haven't been able to use my plugins or theme in 3 days.

![](https://i-work-at-the.cocaine.institute/Lizzy63f084962NHV9Ay1Dd33.png)

**Comment by lexisother** [comment]
Instead of waiting for three days, just make the folder yourself until we fix it...?

**Comment by LizAinslie** [comment]
uh, you seem to be missing the bigger issue here. when i build & install my plugins & themes they go in MY `${USER}/.config` and I *presume* when I run Discord as my user, it's not going to read out of the `/root/.config`. Or, if it does, it's going to run into permission problems when it tries to load plugins. Or maybe it'd work if I ran Discord as root but to hell with that.

**Comment by LizAinslie** [comment]
Oh, an update on this: I got a chance to properly test your "fix" yesterday on my day off. I ended up in a perpetual loading state for hours. I let it sit and chug.

**Comment by NotPhantomX** [comment]
A temporary fix is to add the absolute path to src/util.ts
```
export const configPathFn = (): string => {
  switch (process.platform) {
    case "win32":
      return join(process.env.APPDATA || "", REPLUGGED_FOLDER_NAME);
    case "darwin":
      return join(process.env.HOME || "", "Library", "Application Support", REPLUGGED_FOLDER_NAME);
    default:
      return join("/home/your user directory/.config/", REPLUGGED_FOLDER_NAME);
    // if (process.env.XDG_CONFIG_HOME) {
    //   return join(process.env.XDG_CONFIG_HOME!, REPLUGGED_FOLDER_NAME);
    // }
    // return join(process.env.HOME || "", ".config", REPLUGGED_FOLDER_NAME);
  }
};
```

**Comment by LizAinslie** [comment]
Thanks, I'll give it a shot when I get home.

**Comment by asportnoy** [comment]
@NotPhantomX I linked #408 which should fix this issue. Feel free to try on that branch to see if it works for you. If not, let me know.

**Comment by NotPhantomX** [comment]
> @NotPhantomX I linked #408 which should fix this issue. Feel free to try on that branch to see if it works for you. If not, let me know.

I have confirmed that that branch successfully finds the right .config directory and successfully injects.

**Comment by asportnoy** [comment]
Great! Will merge it now.

**Comment by LizAinslie** [comment]
Pog, thanks y'all :)
