### ISSUE TITLE
replugged plugin install links not working 

### ISSUE THREAD

**Issue by Dialgatrainer02** [replugged-org/replugged#396]
### Describe the bug

when installing plugins the install urls cant connect to the client correctly and no confirmation pop up appears 

### Reproduction steps

1.go to #plugin-links 
2.try to install plugin via link
3.no pop up and plug in not installed

### Expected behavior

plugin to install correctly 

### Actual behavior

doesn't connect to client properly and dosent install 

### Additional information

im an on endeavour os wayland i have made sure discord isnt in xwayland and i can install plugins manualy by going to realses and manually moving the files

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by asportnoy** [comment]
Can you confirm that Replugged is fully up to date?

**Comment by bop34** [comment]
Also are there any console errors?

**Comment by Dialgatrainer02** [comment]
> Can you confirm that Replugged is fully up to date?

i cant install the git version which is a separate issue but i have been using the one on the aur 
https://aur.archlinux.org/packages/replugged-electron-git but im not sure if this is up to date

**Comment by Dialgatrainer02** [comment]
> Also are there any console errors?
i cant find any console is it in replugged settings? if so i cant get to them 
![image](https://user-images.githubusercontent.com/96637854/219854076-1c5f929c-c5e2-462f-b5d2-eb5904bbd439.png)

**Comment by asportnoy** [comment]
Yep that's definitely not up to date. Please follow the instructions from our [installation page](https://replugged.dev/installation).
