### ISSUE TITLE
Injection List

### ISSUE THREAD

**Issue by Tharki-God** [replugged-org/replugged#400]
### Describe the feature request

it would be nice if the patched function have a list specifically an set of string with names/id of plugins it have been patched from. 

### Why should this be added?

to make it easy for plugin devlopers to check if an function have already been patched 

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by FedeIlLeone** [comment]
We have decided not to include this anymore. Refer to https://github.com/replugged-org/replugged/pull/491#issuecomment-1599756144.
