### ISSUE TITLE
Toast module fails to load

### ISSUE THREAD

**Issue by thewilloftheshadow** [replugged-org/replugged#401]
### Describe the bug

Trying to toggle a plugin off using the settings page fails because the toast module does not load

### Reproduction steps

1. Open replugged settings
2. Go to the plugins tab
3. Try to toggle a plugin

### Expected behavior

The plugin disables and a toast appears

### Actual behavior

The toggle does not change and the error is shown in the console

### Additional information

![image](https://user-images.githubusercontent.com/35580099/221702912-e9c49fec-0063-4415-b35f-db391e365077.png)
<img width="1440" alt="CleanShot 2023-02-27 at 16 44 39@2x" src="https://user-images.githubusercontent.com/35580099/221703006-b0aacf00-a113-4cac-abff-ac159f640770.png">

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by asportnoy** [comment]
Fixed in #403
