### ISSUE TITLE
Replugged badges fail to load

### ISSUE THREAD

**Issue by thewilloftheshadow** [replugged-org/replugged#402]
### Describe the bug

Trying to load Replugged badges crashes the client

### Reproduction steps

Various methods: 
- View the profile of a user who has replugged badges
- Open DMs with a user who has replugged badges
- Open your own settings if you have badges

### Expected behavior

Badges are shown

### Actual behavior

The client crashes

### Additional information

<img width="658" alt="CleanShot 2023-02-27 at 16 49 21@2x" src="https://user-images.githubusercontent.com/35580099/221704507-c8c5a54d-e4f1-47d3-923f-29b458274913.png">
<img width="968" alt="CleanShot 2023-02-27 at 16 49 40@2x" src="https://user-images.githubusercontent.com/35580099/221704593-cf96799a-7d51-4d9f-80f0-3b26d6e4842d.png">

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by asportnoy** [comment]
Fixed in #403
