### ISSUE TITLE
Setting position toggle

### ISSUE THREAD

**Issue by Tharki-God** [replugged-org/replugged#405]
### Describe the feature request

an option to change replugged setting's section position it would be nice if we could select after which setting we can place the rp setting section or if after none and at the start.

### Why should this be added?

because it makes the settings user friendly

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by lexisother** [comment]
This isn't "user-friendly". What if someoene makes a typo in the string that denotes where they want to put the settings? It will break.

**Comment by Tharki-God** [comment]
> This isn't "user-friendly". What if someone makes a typo in the string that denotes where they want to put the settings? It will break.

make it a dropdown why do you wanna make it text input

**Comment by asportnoy** [comment]
Relevant XKCD: https://xkcd.com/1172/

**Comment by Tharki-God** [comment]
what

**Comment by Tharki-God** [comment]
![image](https://user-images.githubusercontent.com/73281112/221900110-79f7dc84-1440-4dad-8a76-52ca599402a9.png)
something like this is what i asked for
