### ISSUE TITLE
Notice (banner) on install

### ISSUE THREAD

**Issue by bop34** [replugged-org/replugged#406]
### Describe the feature request

Make a modal appear when Discord for the first time after Replugged is installed.

### Why should this be added?

This make it much clearer to the user that Replugged has successfully been installed.

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by asportnoy** [comment]
Should be a notice (banner), not a modal.

**Comment by mrhappyma** [comment]
I'd like to give this a shot

**Comment by asportnoy** [comment]
Assigned
