### ISSUE TITLE
Installing doesn't work on NodeJS Nightly, works fine on LTS

### ISSUE THREAD

**Issue by ValenTranshuman** [replugged-org/replugged#414]
### Describe the bug

Full Bug can be found on Replugged Discord [here](https://discord.com/channels/1000926524452647132/1006383180309352538/threads/1081918683951136820)

Trying to install with current NodeJSNightly throws the following error: 
![image](https://user-images.githubusercontent.com/69856775/222961822-44d74d08-84dd-4e85-bbd5-2500f95c4eb2.png)

switching to NodeJS LTS works fine and fixes the error.

Please update documentation at https://replugged.dev/download to include this as a requirement.

### Reproduction steps

1. Install NodeJS nightly from https://nodejs.org/download/nightly/ .
2. Follow installation documentation from https://replugged.dev/download .
3. Get the error described above.

### Expected behavior

Installation should work fine.

### Actual behavior

esbuild does not support NodeJS 20.
Installation fails with exist code 1.

### Additional information

OS Version: Windows 11 Enterprise Insider Preview 25309.1000
NodeJS Version: node-v20.0.0-nightly202303050
Git version: Current
Discord Version: Irrelevant to bug.

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by asportnoy** [comment]
If it's nightly then I think you should assume things might not work properly.
