### ISSUE TITLE
[Feature Request] add queue system to open modal

### ISSUE THREAD

**Issue by Deepfried-Chips** [replugged-org/replugged#45]
**Describe the feature request**
Add queue to openModal, right now it does have a sort of queue system but it starts mismatching data by the 2nd modal

**What module would it be for?**
`powercord/modal` module

**Expected behavior**
Everytime a modal is closed, it checks if another one is queued, grabs the data for the new modal and opens it

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
