### ISSUE TITLE
Common modules

### ISSUE THREAD

**Issue by notKnei** [replugged-org/replugged#451]
### Describe the bug

The common modules `messages`, `channels`, `guilds`, and `users` are all `Proxy` which don't contain the functions as documented.

### Reproduction steps

1. Open the console
2. Enter `replugged.common` and note how `messages`, `channels`, `guilds`, and `users` are `Proxy`
the 

### Expected behavior

The values of these should match the documented values below.
[messages](https://guide.replugged.dev/docs/plugins/modules/common#messages)
[channels](https://guide.replugged.dev/docs/plugins/modules/common#channels)
[guilds](https://guide.replugged.dev/docs/plugins/modules/common#guilds)
[users](https://guide.replugged.dev/docs/plugins/modules/common#users)

### Actual behavior

The values are Proxies which don't contain the proper values.

### Additional information

![image](https://user-images.githubusercontent.com/76569087/232122686-6641ba74-fd12-4939-896c-53e8d39f1bc9.png)

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by Vendicated** [comment]
have you ever tried accessing any of the documented members?

**Comment by notKnei** [comment]
> have you ever tried accessing any of the documented members?

Just lead to errors

**Comment by notKnei** [comment]
Sorry for the invalid bug report, after restarting the function is now working just fine. Still not sure what the cause of this was though

**Comment by asportnoy** [comment]
If you want to see the properties in devtools, use `.all()` on it.
