### ISSUE TITLE
Bad config folder perms on linux install

### ISSUE THREAD

**Issue by SomeAspy** [replugged-org/replugged#455]
### Describe the bug

Perms are incorrect on the default `.config/replugged` folder install.
the folder is owned by root instead of the user that owns `.config/`
![image](https://github.com/replugged-org/replugged/assets/33640860/d3e67236-8d65-4a55-b949-f45a8ea9725b)
This breaks automatic plugin/theme installation via links inside discord. 

### Reproduction steps

1. Install Replugged
2. `ls -l ~/.config`
3. Observe incorrect permissions for current user.

### Expected behavior

permissions should be owned by the current user

### Actual behavior

folder is owned by root.

### Please confirm the following

- [X] I made sure this is not related to an external plugin or a theme
- [x] I checked if Discord and Replugged are up to date
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by asportnoy** [comment]
This is a known issue on Linux in general and can be fixed by CHOWNing the folder.

**Comment by momu54** [comment]
![Screenshot_20230610-210121.png](https://github.com/replugged-org/replugged/assets/96234201/56570254-c9d3-4816-a1c8-0a1aa562b695)

Maybe we can add `chown` there after `mkdir`?
If I really understand the codes.

**Comment by lexisother** [comment]
...no, that `mkdir` is completely unrelated.

**Comment by momu54** [comment]
Ok, I'll research the code deeply tomorrow if I don't forget
And I'll try to help that if I can
