### ISSUE TITLE
Replugged not detecting Clyde

### ISSUE THREAD

**Issue by Kaisarion** [replugged-org/replugged#46]
**Describe the bug**
Error upon entering updater after erradicating Clyde on first setup, disabling most client features.

**To Reproduce**
1. Erradicate Clyde in General Settings on setup
2. Restart Replugged
3. Observe in Settings -> Updater

**Expected behavior**
Clyde should be erradicated just fine & updater should be opened successfully
Screenshot:
![image](https://user-images.githubusercontent.com/60671860/182534782-fa1d089d-f7e0-475c-92e6-5de622be991e.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.4

**Additional context**
 - [X] I checked if Discord and/or Replugged are up to date
 - [X] I made sure this is not related to an external plugin or a theme

**Comment by Vap0r1ze** [comment]
I can see from your settings panel that you're running Powercord rather than Replugged, this is the repo for Replugged.
If you wanna migrate to Replugged the instructions are [✧･ﾟ: *✧･ﾟ:*  heree  *:･ﾟ✧*:･ﾟ✧](https://github.com/replugged-org/replugged/wiki/Installation#migrating-from-powercord)

**Comment by Kaisarion** [comment]
Incorrect. It is still replugged and I had this conversation with a member in the discord. On Aug 3, 2022, at 3:37 PM, Justice Almanzar ***@***.***> wrote:﻿
I can see from your settings panel that you're running Powercord rather than Replugged, this is the repo for Replugged.
If you wanna migrate to Replugged the instructions are ✧･ﾟ: ✧･ﾟ:  heree  :･ﾟ✧:･ﾟ✧

**Comment by Vap0r1ze** [comment]
I only see three messages in the Discord and none of them are related to this. I have no way of knowing how that conversation went

**Comment by FifiTheBulldog** [comment]
Resolved on Discord, it was an issue with overwriting pc- plugins with the ones from Powercord.
