### ISSUE TITLE
Add timeout for plugin ignition

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#473]
Currently, a plugin can be loading forever and will block the ignition finishing. We should add a timeout for a plugin loading (maybe 5s), at which point we'll log an error and continue with the ignition. If the plugin loads later then great, but the ignition should be unblocked by that.

**Comment by Tharki-God** [comment]
> Currently, a plugin can be loading forever and will block the ignition finishing. We should add a timeout for a plugin loading (maybe 5s), at which point we'll log an error and continue with the ignition. If the plugin loads later then great, but the ignition should be unblocked by that.

also, make it a manifest key that if it will take longer every time then just skip even that 5s wait and log that it's in the queue for lazy loading or something.

**Comment by asportnoy** [comment]
No, plugins should not be blocking startup for things like that. If you have something that consistently will take a while to start up then you should not be awaiting it.

**Comment by Tharki-God** [comment]
> No, plugins should not be blocking startup for things like that. If you have something that consistently will take a while to start up then you should not be awaiting it.

thats what I meant, just put it in the queue for the background instead of waiting for plugin if its specified that it will take time. just make it so plugins doesnt need to load fully before discord get loads.

**Comment by bop34** [comment]
I’ll take this if that’s okay.

**Comment by asportnoy** [comment]
All yours @bop34
