### ISSUE TITLE
Can't install plugins from Store

### ISSUE THREAD

**Issue by xXChampionsXx** [replugged-org/replugged#485]
### Describe the bug

Everytime I click on any install button on the store webpage it just shows this error:
![image](https://github.com/replugged-org/replugged/assets/60485613/05f3f7de-8a80-4f1b-917c-030eb6e111d8)

### Reproduction steps

1. Install replugged
2. Try to install plugin

### Expected behavior

The plugin installs

### Actual behavior

It doesn't

### Additional information

I tried it on my laptop with a fresh discord install and the same thing happens.

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by asportnoy** [comment]
Make sure you disable any content blockers. Brave is known to cause issues, for example.

**Comment by asportnoy** [comment]
Closing as stale due to no response

**Comment by xXChampionsXx** [comment]
I didn't see the reply. Disabling content blocker in brave did fix it!
