### ISSUE TITLE
Don't enable Themes/Plugins automatically (especially Themes) if installed

### ISSUE THREAD

**Issue by SparkleArts** [replugged-org/replugged#493]
### Describe the feature request

By Default it should not enable any Themes or Plugins if installed from Store (at least there it is automatically enabled.)

### Why should this be added?

Here is the Issue I got:
I have a theme called ClearVision v6 installed from Store. Replugged automatically enable it.

Now I want to install a new Theme called LilyPichu by Nyria from Store. Replugged automatically enable it while ClearVision v6 is enabled.

Now I want to disable ClearVision v6. So I go the settings click the Themes Button and I got a crash. Before I didn't have one at all if I try to open the Themes Menu.

### Additional information
Oh by the way I cannot use Discord Canary alongside with Replugged anymore because of this ********!

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by asportnoy** [comment]
Sounds like the real problem here is the crash, not that the theme is automatically enabled. What version of Replugged are you on?

**Comment by SparkleArts** [comment]
the latest version of Replugged.

**Comment by asportnoy** [comment]
Please screenshot the info at the bottom of settings.

**Comment by SparkleArts** [comment]
Canary 209796 (db41d80)
Host 1.0.70 (34277) 
Windows 10 64-Bit (10.0.19044)
Replugged v4.4.2

**Comment by SparkleArts** [comment]
Is it normal that I get the Crash Screen where I can click the Reload after I update a Theme or Plugin from the Updater and restart Discord?

**Comment by asportnoy** [comment]
> Is it normal that I get the Crash Screen where I can click the Reload after I update a Theme or Plugin from the Updater and restart Discord?

I think that happens when you have Devtools open.

**Comment by asportnoy** [comment]
Is this still an issue?

**Comment by SparkleArts** [comment]
This is not an issue anymore. It was only one time issue.
