### ISSUE TITLE
Discord Experiments are gone

### ISSUE THREAD

**Issue by Nono-04** [replugged-org/replugged#50]
**Describe the bug**
The Discord Experiments dont show up anymore

**To Reproduce**
1. Enable Discord Experiments
2. Restart/Reload Discord
3. Discord Experiments are not there

**Expected behavior**
The Discord Dev Tools and Experiments should show up

**Desktop (please complete the following information):**
 - OS: WIndows
 - Replugged version: 5ffb67f

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
![image](https://user-images.githubusercontent.com/49478749/182848665-b2734691-3022-4761-a3d5-1415a1f71bc0.png)

**Comment by asportnoy** [comment]
This is a [known issue](https://discord.com/channels/1000926524452647132/1000955953618899084/1003984103248515153), I don't think anyone has figured out a fix yet. If anyone is able to figure it out, go ahead and PR.

**Comment by FifiTheBulldog** [comment]
There's a snippet in #js-snippets that works around the new changes, so we can use that. https://discord.com/channels/1000926524452647132/1000955970681319494/1004036518937116752

**Comment by lleyton** [comment]
Fixed by #68

**Comment by asportnoy** [comment]
It didn't
