### ISSUE TITLE
Install addon command

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#528]
[blocked until the commands API is finished]

We should add a command to open the install flow: `/install <id> [source]`. Then we can share this command in the store pages as an alternative when a user's browser is unable to connect.

**Comment by asportnoy** [comment]
Yours now

**Comment by trollo2** [comment]
anything new

**Comment by asportnoy** [comment]
Haven't had a chance to rest after the latest update but this is still planned for the v4.7.0 update
