### ISSUE TITLE
Limit QuickCSS Editor Size

### ISSUE THREAD

**Issue by DracoClaw** [replugged-org/replugged#536]
### Describe the feature request

Limit the height of the QuickCSS Editor. Currently it just keeps going and can get to be quite long. The solution would be setting a max height  for the editor and then having a scrollbar inside it.

### Why should this be added?

Scrolling all the way to the bottom of the page is a pain.

### Please confirm the following

- [X] This is a feature request for Replugged itself, not a feature request for a plugin or theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this feature has not been requested before.

**Comment by FedeIlLeone** [comment]
This has been fixed with #632 .
