### ISSUE TITLE
Make profile badges re-fetch after an hour

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#54]
After an hour, profile badges should be re-fetched when you open their profile. If you're interested in taking this on, please leave a comment.

**Comment by hummusbird** [comment]
ill give this a go :P

**Comment by LandenStephenss** [comment]
https://github.com/replugged-org/replugged/blob/main/src/Powercord/coremods/badges/index.js#L17-L30

Just set this to a useCallback or w/e and have it refetch on a `setInterval`, or use a `setInterval` to just remove the user cache.

Better yet you could use a cron job to do it every hour, that'd probably eat less resources than a setInterval.

**Comment by asportnoy** [comment]
I would just have it cache the time fetched and if that was over an hour ago then re-fetch it instead of using the cache.

**Comment by LandenStephenss** [comment]
Who said anything about using the cache being used?

`setInterval(() => void 0, 3.6e+6)` would literally run every hour, not to mention cron jobs work with the system clock so you could just do `0 * * * *` as the schedule and it'd to run at 00:00, 01:00, 02:00, etc.

If you remove the user cache then the badges plugin will just see that it doesn't have the user in the cache and fetch it lol

**Comment by asportnoy** [comment]
To clarify, we don't want it to re-fetch immediately after the hour is up. Just if they open someone's profile (which calls the code you linked above)

**Comment by LandenStephenss** [comment]
you wouldn't be refetching??? you'd just remove the user's badge after an hour

**Comment by asportnoy** [comment]
We wouldn't be fetching right away, but the next time their profile is opened, since the cache is too old, it wouldn't use that and would instead fetch as if it wasn't in the cache at all.

**Comment by LandenStephenss** [comment]
Is that not what you want lol

**Comment by asportnoy** [comment]
If their profile isn't opened again then it's not necessary to re-fetch it. Same reason we don't fetch for all users right away.

**Comment by LandenStephenss** [comment]
dude are you handicapped or something.

Removing the cache is not going to immediately refetch the cache, it will literally just remove it. Then once the profile is opened it will be refetched, like you said above
> Just if they open someone's profile (which calls the code you linked above)
Cmon man, think outside of the box a little bit

I mentioned refetching above but i also mentioned just removing the cache and that is the only thing i have mentioned in the past few comments while going back and forwards

**Comment by Vendicated** [comment]
what asp means is that the cache also stores a Date object with info on when this info was cached. Then when the cache is accessed, it checks whether this Date is more than an hour old. If so it refetches. No setTimeout needed

**Comment by LandenStephenss** [comment]
I get that, but that just seems like it's storing pointless data. Considering it'll keep the data for however long the user doesn't reset their discord, it isn't much but it's some. Removing it seems better since then it'd be gone. What's the point of keeping it if it's not gonna get used again anyways (saying that because most people aren't checking user profiles all that often)

**Comment by Vendicated** [comment]
storing a few bytes of unnecessary data is more performant and easier than setTimeout, it really doesn't matter much

**Comment by hummusbird** [comment]
ok u guys do this i dont wanna anymore

**Comment by asportnoy** [comment]
👍
