### ISSUE TITLE
Unable to Scroll During Message Sending

### ISSUE THREAD

**Issue by Kaisarion** [replugged-org/replugged#56]
**Describe the bug**
Upon *spamming* your opponent, messages will be stuck in the sending queue to avoid spam per Discord gamebook which will also make you unable to scroll.

**To Reproduce**
1. Open a channel or DM channel where you have enough messages to be able to scroll
2. Spam a few things (I chose Z's) until it slows down your ability to send the messages instantly
3. Try to scroll, observe.

Screen Recording doing of reproduction:

https://user-images.githubusercontent.com/60671860/183235039-a4f4853d-2c6d-44a8-9da6-0b6fa5a731d8.mov

**Expected behavior**
Should be able to scroll up during message sending queue.

**Desktop:**
 - OS: MacOS Monterey 12.4 (21F79)
 - Replugged version: Replugged main (a80999e)

**Additional context**
 - [X] I checked if Discord and/or Replugged are up to date
 - [X] I made sure this is not related to an external plugin or a theme

**Comment by Vendicated** [comment]
Just don't spam? Also this probably happens on stock discord too, have you checked?

**Comment by kantraksel** [comment]
I reproduced it on Windows (Stable/Canary, clean clients) and this bug is not related to replugged, however it would be nice to fix the bug.

**Comment by asportnoy** [comment]
Was able to reproduce this without Replugged so this is a Discord issue.
