### ISSUE TITLE
Enable and Disable Quick CSS

### ISSUE THREAD

**Issue by Snare-Hawk** [replugged-org/replugged#59]
**Describe the feature request**
An easy way to enable and disable Quick CSS.

**What Plugin would it be for?**
N/A

**Expected behavior**
It would enable and disable Quick CSS, easily.

**Comment by thennothinghappened** [comment]
am working on this

**Comment by thennothinghappened** [comment]
https://user-images.githubusercontent.com/35243139/183823649-314d3b4c-4b48-436f-b0f9-c305d949f310.mp4
I've got it working!

**Comment by thennothinghappened** [comment]
close this now?

**Comment by lleyton** [comment]
oh yeah, oop
