### ISSUE TITLE
Deeplinks don't work with MacOS Safari

### ISSUE THREAD

**Issue by Nygosaki** [replugged-org/replugged#599]
### Describe the bug

The deeplinks to install plugins and themes from the replugged website via the "install" button don't work, saying 
```Could not connect to Replugged, please make sure Discord is open with the latest version of Replugged installed and try again.```
When attempting to install plugins or themes in safari

### Reproduction steps

1. Use MacOS
2. Launch plugged in discord
3. Click the "install" button on any plugin or theme from the replugged store through Safari

### Expected behavior

For the installation to begin

### Actual behavior

A error saying ```Could not connect to Replugged, please make sure Discord is open with the latest version of Replugged installed and try again.``` is shown

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [x] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by gaygoblin** [comment]
This seems to be happening to me, and I'm om win11.
