### ISSUE TITLE
Discord (on Linux) locks up when clicking 'Open Folder' hyperlink in settings

### ISSUE THREAD

**Issue by furokku** [replugged-org/replugged#61]
**Describe the bug**
Discord locks up when clicking 'Open folder' on any entry in the Plugins or Themes tab of settings.
I do not know whether it is OS-specific, as I have only tested it on Linux.

**To Reproduce**
1. Open settings in Discord with Replugged injected
2. Go to the Plugins or Themes tab
3. Click the 'Open Folder' button on any plugin or theme entry
4. See that Discord has locked up until you close the file manager window

**Expected behavior**
Discord should not have locked up, instead continuing to run as usual.

**Desktop (please complete the following information):**
 - OS: Arch Linux, latest
 - Replugged version: f93f247

**Additional context**
 - [ x ] I checked if Discord and/or Replugged are up to date
 - [ x ] I made sure this is not related to an external plugin or a theme
 
This appeared in Discord Canary, but it is likely to be present on other versions as well.
I've attached a video in hopes of making the issue more clear.

https://user-images.githubusercontent.com/104717368/183283853-a5a289b2-1e6b-4904-be59-b252cccca8f4.mp4

**Comment by bop34** [comment]
I'm using Arch Linux with KDE plasma and I am not experiencing this.

**Comment by thennothinghappened** [comment]
> I'm using Arch Linux with KDE plasma and I am not experiencing this.

im on arch + i3, happens for me

**Comment by Vendicated** [comment]
I also cannot reproduce this. Likely an issue with your file explorer? Could you paste the output of the following commands? And also see if the second one freezes your terminal like Discord (try typing in it)

```sh
xdg-mime query default $(xdg-mime query filetype /)
XDG_UTILS_DEBUG_LEVEL=2 xdg-open /
```

**Comment by furokku** [comment]
> I also cannot reproduce this. Likely an issue with your file explorer? Could you paste the output of the following commands? And also see if the second one freezes your terminal like Discord (try typing in it)
> 
> ```shell
> xdg-mime query default $(xdg-mime query filetype /)
> XDG_UTILS_DEBUG_LEVEL=2 xdg-open /
> ```

```
~ » xdg-mime query default $(xdg-mime query filetype /)

pcmanfm.desktop
~ » XDG_UTILS_DEBUG_LEVEL=2 xdg-open /
Selected DE generic
Running file --brief --dereference --mime-type "/"
Checking /home/furokku/.config/mimeapps.list
Checking /home/furokku/.local/share/applications/mimeapps.list
Checking /home/furokku/.local/share/applications/defaults.list and /home/furokku/.local/share/applications/mimeinfo.cache
Checking /home/furokku/.local/share/applications/defaults.list and /home/furokku/.local/share/applications/mimeinfo.cache
Checking /usr/local/share//applications/defaults.list and /usr/local/share//applications/mimeinfo.cache
Checking /usr/local/share//applications/defaults.list and /usr/local/share//applications/mimeinfo.cache
Checking /usr/share//applications/defaults.list and /usr/share//applications/mimeinfo.cache

** (pcmanfm:8688): WARNING **: 21:58:45.646: The directory '~/Templates' doesn't exist, ignoring it
```

Semms like it does freeze up my terminal, so it's probably a per-system basis, which would be no fault of Replugged. I'll look into it on my end, sorry for creating an issue that doesn't actually apply to Replugged.
