### ISSUE TITLE
Stuck on "Connecting..."

### ISSUE THREAD

**Issue by nbourre** [replugged-org/replugged#620]
### Describe the bug

I am new to Replugged. When adding a plugin or a theme, the toast is stuck on "Connecting..." and nothing happens in the plugged Discord. Am I missing something?

### Reproduction steps

1. Go on "Replugged.dev"
2. Find a plugin
3. Click Intall

### Expected behavior

The plugin is added to Discord.

### Actual behavior

The toast is stuck on "Connecting..." and nothing happens.

![msedge_0Wgau8RKUL](https://github.com/replugged-org/replugged/assets/2332679/bfef79f4-fa29-461c-9e2e-eb86327f1946)

### Please confirm the following

- [X] I checked if Discord and Replugged are up to date
- [X] I made sure this is not related to an external plugin or a theme
- [X] [I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure this bug has not been reported before.

**Comment by FedeIlLeone** [comment]
This issue has been fixed as of v4.7.10.
