### ISSUE TITLE
multiple git commits

### ISSUE THREAD

**Issue by Wolfkid200444** [replugged-org/replugged#63]
**Describe the bug**
So when theres a new commit from the main repo instead of showing Replugged and the commit
i get different plugins which contain the same commit message from the main repo but this doesnt happen on other plugins only from replugged

**To Reproduce**
1. wait for a commit from replugged
2. done

**Expected behavior**
it should only show Replugged

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit
 - Replugged version: f93f247

**Additional context**
 - [ x ] I checked if Discord and/or Replugged are up to date
 - [ x ] I made sure this is not related to an external plugin or a theme
 
![image](https://user-images.githubusercontent.com/32025746/183312020-89a7f1de-0422-4307-974a-70c416b9fa51.png)

**Comment by asportnoy** [comment]
I can't reproduce this. Can you try uninstalling and reinstalling the plugins? Also make sure the plugins are a git repo and pointing to the correct place.

**Comment by Wolfkid200444** [comment]
It seems to fixed it somehow
