### ISSUE TITLE
Plugin disappearing from updater list

### ISSUE THREAD

**Issue by Wolfkid200444** [replugged-org/replugged#65]
**Describe the bug**
Has the title suggest the plugins keep disappearing from the updater list
whenever u click for `check for Updates` while having few plugins on ur list

**To Reproduce**
Have 2 (only tested it with replugged update) or probably more plugins which have a update and click Check for Updates this will make one or two plugins disappear from the list.

**Expected behavior**
All ur plugins which have a update should be in the list with the commit for update

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Replugged version: 86ae1cb

**Additional context**
 - [ x ] I checked if Discord and/or Replugged are up to date
 - [ x ] I made sure this is not related to an external plugin or a theme
 

https://user-images.githubusercontent.com/32025746/183549173-c1aba8a5-aae3-4dc6-a344-43a56b5b14f9.mp4

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
