### ISSUE TITLE
Make plugin links look like build overrides

### ISSUE THREAD

**Issue by FifiTheBulldog** [replugged-org/replugged#69]
**Describe the feature request**
Use Discord’s build override component, but for plugin links. That way it hides the fairly lengthy URL and fits right in with how Discord does things. (From the thread on suggestion 32 on the Discord server)

**What Plugin would it be for?**
N/A

**Expected behavior**
N/A

**Comment by lexisother** [comment]
I am working on this already: #28

**Comment by asportnoy** [comment]
Could you make it work without the store and then implement that letter for store plugins?

**Comment by Vap0r1ze** [comment]
It should be noted that #28 at the moment is implimenting a differently styled embed than this issue is asking for (reusing Build Override components)

**Comment by lexisother** [comment]
> Could you make it work without the store and then implement that letter for store plugins?

It already works without store plugins. But I thought I would keep it draft until the store was added so I could migrate the code.

**Comment by lexisother** [comment]
> It should be noted that #28 at the moment is implimenting a differently styled embed than this issue is asking for (reusing Build Override components)

No it isn't. It's quite literally a build override embed. Did you even test locally? (yes, there's a bug to squash. but I stopped working due to the store not being present.)

https://user-images.githubusercontent.com/54973868/183860413-55daf2e9-ff31-4042-8a5c-1586936687a4.mp4

**Comment by Vap0r1ze** [comment]
I'm so sorry lol, it was a poorly made assumption
