### ISSUE TITLE
Can't Paste in Quick CSS Pop-out

### ISSUE THREAD

**Issue by DracoClaw** [replugged-org/replugged#71]
**Describe the bug**
When the Quick CSS window is popped out, I can not paste into it.

**To Reproduce**
Go to Settings > Themes > Quick CSS
Click Pop Out
Ctrl + V

**Expected behavior**
The text in the clipboard should be pasted in.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19043)
 - Replugged version: main (ed66152)

**Additional context**
 - [X] I checked if Discord and/or Replugged are up to date
 - [X] I made sure this is not related to an external plugin or a theme

**Comment by asportnoy** [comment]
Pretty sure I had this issue in the past so I'm gonna mark it as verified.

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
