### ISSUE TITLE
Install Plugin Links Not Working

### ISSUE THREAD

**Issue by Snare-Hawk** [replugged-org/replugged#72]
**Describe the bug**
When I click a plugin install link (e.g. <https://replugged.dev/install?url=https://github.com/Juby210/bdCompat>), it crashes my client immediately. When I try in my browser, it doesn't open Discord and simply says that it was unreachable.

**To Reproduce**
Click link that should install a plugin.

**Expected behavior**
Should be further prompted to install plugin.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19044)
 - Replugged version: Replugged main (2318a44)

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by Vap0r1ze** [comment]
browser install wont work until they update and restart the backend, but the client crash shouldnt happen
