### ISSUE TITLE
Cannot access plugin repositories

### ISSUE THREAD

**Issue by bop34** [replugged-org/replugged#75]
**Describe the bug**
When attempting to open any plugin's repo (under Plugins section in user settings), [https://github.com/replugged-org/replugged.git](url) is opened in the browser, which redirects to [https://github.com/replugged-org/replugged](url).

**To Reproduce**

1. Open user settings
2. Open the Plugins section on the left hand side
3. Locate any plugin
4. Click on the Repository link/button
5. Get sent to the Replugged GitHub

**Expected behavior**
The plugin's GitHub repo opens.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Replugged version: main aa31a70

**Additional context**
 - [X] I checked if Discord and/or Replugged are up to date
 - [X] I made sure this is not related to an external plugin or a theme
 
This bug does not happen for the LMGTFY plugin for some reason.

**Comment by thennothinghappened** [comment]
seems to be working just fine for me. are you sure the plugins you're testing have a repo linked?

**Comment by asportnoy** [comment]
We should probably make it detect when there's no repo and don't show the button.

**Comment by bop34** [comment]
Yeah I think that's what it is. It's probably smart to either hide the button or have some text saying it's unlinked.

**Comment by bop34** [comment]
Oh wow, upon further examination this does appear to be my fault. Almost no of my plugins have a linked repo for some reason. Still, the button should hide if there is none.

**Comment by asportnoy** [comment]
Likely you downloaded the plugins with the "Download ZIP" button on GitHub, which doesn't have the git info. I'll create a separate issue for the repo button hiding.
