### ISSUE TITLE
Hide "Repository" button in Plugin cards if there's no git repository

### ISSUE THREAD

**Issue by asportnoy** [replugged-org/replugged#88]
If a plugin doesn't have a git repository, the repository button in the settings card currently opens Replugged git repository. Instead, the button should just be hidden.
Discovered in #75

**Comment by hummusbird** [comment]
Ill take this one!

**Comment by hummusbird** [comment]
@asportnoy this can be closed now :P

**Comment by asportnoy** [comment]
For next time, you can use closong keywords so it's closed automatically. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
