### ISSUE TITLE
Missing Discord status transition animations

### ISSUE THREAD

**Issue by Filipianosol** [replugged-org/replugged#97]
**Description**
Unlike vanilla Discord, status transition animations don't seem to work on Replugged. Tested on a fresh Replugged stable branch installation. I've looked in settings, the Discord server's #known-issues channel and #misc-support's pins, GitHub issues, and searched for `animation` in the Replugged server. Couldn't find any mention of this issue. Same thing happened on Powercord.

https://user-images.githubusercontent.com/12639838/184123108-b9e9ad18-8100-4626-a364-92d2b0e28ff8.mp4

**To reproduce**
Change your status or start typing and look at your status. Notice the lack of Discord's normal smooth status transition animation.

**Expected behavior**

https://user-images.githubusercontent.com/12639838/184123152-f14a48cb-9a82-4b6d-9299-2909384ce3aa.mp4

**Desktop**
 - OS: Windows 10 64-bit
 - Replugged version: 6a525c1

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by asportnoy** [comment]
Can you confirm that it happens with no plugins?

**Comment by Filipianosol** [comment]
> Can you confirm that it happens with no plugins?

Yeah. I just took the following steps to make absolutely sure it's nothing on my end:
- Ran `npm run unplug`
- Deleted my cloned `replugged` folder
- Uninstalled Discord
- Deleted `%LOCALAPPDATA%\Discord`
- Deleted `%APPDATA%\discord`
- Installed Discord
- Installed Replugged
- Turned off built-in plugins
- Restarted Replugged

https://user-images.githubusercontent.com/12639838/184194529-0783c631-abb1-43df-b973-3816c2e2d1bc.mp4

**Comment by asportnoy** [comment]
Closing this due to the rewrite.
